[build]
builder = "nixpacks"

[deploy]
startCommand = "uvicorn web:app --host 0.0.0.0 --port $PORT"
healthcheckPath = "/"
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 5

[phases.setup]
aptPkgs = ["ffmpeg", "python3-pip"]
